### ISSUE TITLE
some more info!

### ISSUE THREAD

**Issue by dan-myles** [FrancescElies/wezterm-config#1]
hey! I love your script. I used to use tmux sessionizer by prime and got used to it. Your wezterm config repo is a savior!

I was wondering if you've figured out how to see open "sessions" similar to "Ctrl+B+w" in tmux.

Thanks for ur time and love ur dotfiles.

**Comment by FrancescElies** [comment]
Honestly I didn't write this script either, https://github.com/wez/wezterm/discussions/4796 is where I got it.

Does `Alt-s` do what you need? I it's basically this entry in the keys table `  { key = 's', mods = mods.alt, action = a.ShowLauncherArgs { flags = 'FUZZY|WORKSPACES' } },`

Normally I use `alt-f` for opening repo and `alt-s` for the ones I know I have open, but if you do `alt-f` on existing one it jumps to the one you already have open.
That works well with repos, personally I don't have the need for many ssh sessions, not sure if that's what you need.

Does that help?

**Comment by FrancescElies** [comment]
I am not very familiar with tmux but you can check https://github.com/wez/wezterm/discussions/2329 out

**Comment by dan-myles** [comment]
> Honestly I didn't write this script either, [wez/wezterm#4796](https://github.com/wez/wezterm/discussions/4796) is where I got it.
> 
> Does `Alt-s` do what you need? I it's basically this entry in the keys table ` { key = 's', mods = mods.alt, action = a.ShowLauncherArgs { flags = 'FUZZY|WORKSPACES' } },`
> 
> Normally I use `alt-f` for opening repo and `alt-s` for the ones I know I have open, but if you do `alt-f` on existing one it jumps to the one you already have open. That works well with repos, personally I don't have the need for many ssh sessions, not sure if that's what you need.
> 
> Does that help?

oh my, this is what i was looking for! thanks very much. cant believe i missed that!
